#!/usr/bin/env bash
# Regenerate src/consts.rs from the pinned opus headers.
#
#   ./gen-consts.sh            # rewrite src/consts.rs
#   ./gen-consts.sh --check    # fail if src/consts.rs is not what the headers say
#
# Why generate rather than type them out: every one of these is a bare integer that
# libopus compares against internally, and a single transposed digit gives you a CTL
# that returns OPUS_BAD_ARG at runtime — or worse, sets a different parameter than the
# one named. Deriving them from the same headers the archive was compiled from removes
# that whole class of mistake, and `--check` in CI keeps them from drifting when opus
# is bumped.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"
# The `cd` above makes this correct at run time from anywhere. `source-path=SCRIPTDIR` is
# what makes it resolvable at *check* time too, since shellcheck would otherwise look for
# ../../opus.env relative to wherever it was invoked — which is the repository root in CI,
# two levels up from where this script means.
# shellcheck source-path=SCRIPTDIR
# shellcheck source=../../opus.env
. ../../opus.env

out=src/consts.rs
headers=(include/opus/opus_defines.h include/opus/opus_multistream.h
         include/opus/opus_projection.h)

# Object-like integer #defines only: `$2` must be a bare OPUS_* name, so the
# function-like macros (`OPUS_SET_BITRATE(x)`, whose expansion is a *pair* of
# arguments and means nothing to Rust) are skipped, and `$3` must be an integer, so
# aliases and string macros are too. Trailing doc comments are simply not read.
extract() {
  awk '
    $1 == "#define" && $2 ~ /^OPUS_[A-Z0-9_]+$/ && $3 ~ /^\(?-?[0-9]+\)?$/ {
      value = $3
      gsub(/[()]/, "", value)
      if ($2 in seen && seen[$2] != value) {
        printf "conflicting values for %s: %s and %s\n", $2, seen[$2], value > "/dev/stderr"
        exit 1
      }
      if (!($2 in seen)) { seen[$2] = value; order[++n] = $2 }
    }
    END { for (i = 1; i <= n; i++) printf "pub const %s: i32 = %s;\n", order[i], seen[order[i]] }
  ' "$@"
}

generated="$(
  cat <<EOF
// @generated by gen-consts.sh from the opus $OPUS_VERSION headers — do not edit.
//
// Types: \`i32\` throughout, matching \`audiopus_sys\`'s bindings, because the safe
// wrapper in ../opus-prebuilt is a fork of a crate written against those. libopus takes
// every one of these as a C \`int\`.

EOF
  extract "${headers[@]}"
)"

if [ "${1:-}" = "--check" ]; then
  printf '%s\n' "$generated" | diff -u "$out" - && {
    echo "$out matches the opus $OPUS_VERSION headers"
    exit 0
  }
  echo "$out is stale — run gen-consts.sh" >&2
  exit 1
fi

printf '%s\n' "$generated" > "$out"
echo "wrote $out ($(grep -c '^pub const' "$out") constants from opus $OPUS_VERSION)"
